### ISSUE TITLE
Avira (Antivirus) suspect PUA

### ISSUE THREAD

**Issue by flameddd** [patr0nus/DeskGap#1]
## just FYI

Avira (Antivirus) suspect `DeskGap.exe` as virus

![image](https://user-images.githubusercontent.com/22259196/52683411-af4d3180-2f7d-11e9-99df-261aa332aebf.png)

## ref
 - https://www.avira.com/en/support-threats-summary-product/tid/147899/threat/PUA

**Comment by patr0nus** [comment]
Thanks. I just installed Avira and can confirm this. Will look into it later today.

**Comment by patr0nus** [comment]
@flameddd There is nothing much to worry about.

I rebuilt a brand new `DeskGap.exe` and Avira complained right away. I think it's most likely because DeskGap is something new that Avira never encountered before and its algorithm got paranoid. Actually the [same thing](https://github.com/electron/electron/issues/4485) had happened to electron.

For now signing the program can calm down Avira, as proved by [Pym](
https://www.microsoft.com/store/productId/9PMTMRNBXMPB), which has got reviewed and signed by Microsoft.

**Comment by flameddd** [comment]
Awesome
