### ISSUE TITLE
window.location.reload() breaks window.deskgap and drag

### ISSUE THREAD

**Issue by TorstenDittmann** [patr0nus/DeskGap#41]
Using `window.location.reload()` in code removes the `window.deskgap` reference and all of the drag functionality from elements with the `data-deskgap-drag` attribute.

Reloading with `BrowserWindow` works fine.

**Comment by patr0nus** [comment]
What OS/web engine did you use?

**Comment by TorstenDittmann** [comment]
It occurs on Windows with both EdgeHTML and Trident.

**Comment by patr0nus** [comment]
@TorstenDittmann Hi,

After some googling it turns out this issue has been studied for a long time since the dark age of IE. There are some workaround but never perfect. I think I'll just leave this issue unsolved.

Inconsistencies about navigations happen a lot among different platforms. For cross-platform consistency I would avoid usages of navigation-related functions and events (except ready-to-show and first-time loadURL/loadFile), especially those in BOM.

**Comment by TorstenDittmann** [comment]
Alright. I fully understand you.

For people with the same problem I am gonna edit this post later and add some examples on how to handle this problem. 

Gonna close it later.
